package com.undefined.hydron.infrastructure.db.preloaded

import com.undefined.hydron.domain.models.entities.PresionArterial

// Dataset de Presión Arterial - Solo valores normales sin clasificaciones de hipertensión
val PresionArterialDataSet = listOf(
    // General/Saludable - Rangos normales de presión arterial
    PresionArterial(edadMin = 18, edadMax = 24, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 110, sistolicaMax = 120, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+2-3", aumentoModerado = "+4-6", aumentoSevero = "+8-10"),
    PresionArterial(edadMin = 25, edadMax = 29, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 110, sistolicaMax = 125, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+2-3", aumentoModerado = "+4-6", aumentoSevero = "+8-10"),
    PresionArterial(edadMin = 30, edadMax = 34, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 115, sistolicaMax = 125, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-4", aumentoModerado = "+5-7", aumentoSevero = "+8-11"),
    PresionArterial(edadMin = 35, edadMax = 39, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 115, sistolicaMax = 130, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-4", aumentoModerado = "+5-7", aumentoSevero = "+8-11"),
    PresionArterial(edadMin = 40, edadMax = 44, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 115, sistolicaMax = 130, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-4", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 45, edadMax = 49, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 120, sistolicaMax = 135, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-4", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 50, edadMax = 54, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 120, sistolicaMax = 135, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 55, edadMax = 59, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 125, sistolicaMax = 140, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 60, edadMax = 64, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 125, sistolicaMax = 140, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 65, edadMax = 69, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 130, sistolicaMax = 145, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 70, edadMax = 74, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 130, sistolicaMax = 145, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+8-11", aumentoSevero = "+12-15"),
    PresionArterial(edadMin = 75, edadMax = 79, estadoSalud = GrupoSalud.GENERAL.displayName, sistolicaMin = 135, sistolicaMax = 150, diastolicaMin = 75, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-7", aumentoModerado = "+8-11", aumentoSevero = "+12-16"),

    // Diabetes - Presiones objetivo más bajas
    PresionArterial(edadMin = 18, edadMax = 24, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 100, sistolicaMax = 120, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+3-4", aumentoModerado = "+5-7", aumentoSevero = "+8-11"),
    PresionArterial(edadMin = 25, edadMax = 29, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 100, sistolicaMax = 120, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+3-4", aumentoModerado = "+5-7", aumentoSevero = "+8-11"),
    PresionArterial(edadMin = 30, edadMax = 34, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 105, sistolicaMax = 125, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 35, edadMax = 39, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 105, sistolicaMax = 125, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 40, edadMax = 44, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 110, sistolicaMax = 130, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 45, edadMax = 49, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 110, sistolicaMax = 130, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 50, edadMax = 54, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 115, sistolicaMax = 135, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 55, edadMax = 59, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 115, sistolicaMax = 135, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 60, edadMax = 64, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 120, sistolicaMax = 140, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+5-7", aumentoModerado = "+8-11", aumentoSevero = "+12-15"),
    PresionArterial(edadMin = 65, edadMax = 69, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 120, sistolicaMax = 140, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+5-7", aumentoModerado = "+8-11", aumentoSevero = "+12-15"),
    PresionArterial(edadMin = 70, edadMax = 74, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 125, sistolicaMax = 145, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+5-8", aumentoModerado = "+9-12", aumentoSevero = "+13-16"),
    PresionArterial(edadMin = 75, edadMax = 79, estadoSalud = GrupoSalud.DIABETES.displayName, sistolicaMin = 125, sistolicaMax = 145, diastolicaMin = 70, diastolicaMax = 80, clasificacion = "Normal", aumentoLeve = "+5-8", aumentoModerado = "+9-12", aumentoSevero = "+13-16"),

    // Enfermedad Renal Crónica - Presiones controladas
    PresionArterial(edadMin = 18, edadMax = 24, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 105, sistolicaMax = 125, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 25, edadMax = 29, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 105, sistolicaMax = 125, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 30, edadMax = 34, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 110, sistolicaMax = 130, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 35, edadMax = 39, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 110, sistolicaMax = 130, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 40, edadMax = 44, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 115, sistolicaMax = 135, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 45, edadMax = 49, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 115, sistolicaMax = 135, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 50, edadMax = 54, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 120, sistolicaMax = 140, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-7", aumentoModerado = "+8-11", aumentoSevero = "+12-15"),
    PresionArterial(edadMin = 55, edadMax = 59, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 120, sistolicaMax = 140, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-7", aumentoModerado = "+8-11", aumentoSevero = "+12-15"),
    PresionArterial(edadMin = 60, edadMax = 64, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 125, sistolicaMax = 145, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-8", aumentoModerado = "+9-12", aumentoSevero = "+13-16"),
    PresionArterial(edadMin = 65, edadMax = 69, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 125, sistolicaMax = 145, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-8", aumentoModerado = "+9-12", aumentoSevero = "+13-16"),
    PresionArterial(edadMin = 70, edadMax = 74, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 130, sistolicaMax = 150, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+6-9", aumentoModerado = "+10-13", aumentoSevero = "+14-17"),
    PresionArterial(edadMin = 75, edadMax = 79, estadoSalud = GrupoSalud.ENFERMEDAD_RENAL.displayName, sistolicaMin = 130, sistolicaMax = 150, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+6-9", aumentoModerado = "+10-13", aumentoSevero = "+14-17"),

    // Fibrosis Quística - Presiones ligeramente elevadas por la condición
    PresionArterial(edadMin = 18, edadMax = 24, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 105, sistolicaMax = 125, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 25, edadMax = 29, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 105, sistolicaMax = 125, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+3-5", aumentoModerado = "+6-8", aumentoSevero = "+9-12"),
    PresionArterial(edadMin = 30, edadMax = 34, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 110, sistolicaMax = 130, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 35, edadMax = 39, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 110, sistolicaMax = 130, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-9", aumentoSevero = "+10-13"),
    PresionArterial(edadMin = 40, edadMax = 44, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 115, sistolicaMax = 135, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 45, edadMax = 49, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 115, sistolicaMax = 135, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+4-6", aumentoModerado = "+7-10", aumentoSevero = "+11-14"),
    PresionArterial(edadMin = 50, edadMax = 54, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 120, sistolicaMax = 140, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-7", aumentoModerado = "+8-11", aumentoSevero = "+12-15"),
    PresionArterial(edadMin = 55, edadMax = 59, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 120, sistolicaMax = 140, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-7", aumentoModerado = "+8-11", aumentoSevero = "+12-15"),
    PresionArterial(edadMin = 60, edadMax = 64, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 125, sistolicaMax = 145, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-8", aumentoModerado = "+9-12", aumentoSevero = "+13-16"),
    PresionArterial(edadMin = 65, edadMax = 69, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 125, sistolicaMax = 145, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+5-8", aumentoModerado = "+9-12", aumentoSevero = "+13-16"),
    PresionArterial(edadMin = 70, edadMax = 74, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 130, sistolicaMax = 150, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+6-9", aumentoModerado = "+10-13", aumentoSevero = "+14-17"),
    PresionArterial(edadMin = 75, edadMax = 79, estadoSalud = GrupoSalud.FIBROSIS_QUISTICA.displayName, sistolicaMin = 130, sistolicaMax = 150, diastolicaMin = 70, diastolicaMax = 85, clasificacion = "Normal", aumentoLeve = "+6-9", aumentoModerado = "+10-13", aumentoSevero = "+14-17")
)