package com.undefined.hydron.infrastructure.db.preloaded

import com.undefined.hydron.domain.models.entities.PresionArterial

val PresionArterialDataSet = listOf(
    PresionArterial(
        edadMin = 18,
        edadMax = 29,
        estadoSalud = "Saludable",
        sistolicaMin = 110,
        sistolicaMax = 120,
        diastolicaMin = 80,
        diastolicaMax = 90,
        clasificacion = "Normal",
        aumentoLeve = "+2-3",
        aumentoModerado = "+4-6",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 30,
        edadMax = 39,
        estadoSalud = "Saludable",
        sistolicaMin = 110,
        sistolicaMax = 125,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Normal",
        aumentoLeve = "+2-3",
        aumentoModerado = "+4-6",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 40,
        edadMax = 49,
        estadoSalud = "Saludable",
        sistolicaMin = 115,
        sistolicaMax = 130,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Normal / Prehipertensión",
        aumentoLeve = "+3-4",
        aumentoModerado = "+6-8",
        aumentoSevero = "+10-13"
    ),
    PresionArterial(
        edadMin = 50,
        edadMax = 59,
        estadoSalud = "Saludable",
        sistolicaMin = 120,
        sistolicaMax = 135,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Normal / Prehipertensión",
        aumentoLeve = "+3-4",
        aumentoModerado = "+5-7",
        aumentoSevero = "+8-11"
    ),
    PresionArterial(
        edadMin = 60,
        edadMax = 69,
        estadoSalud = "Saludable",
        sistolicaMin = 125,
        sistolicaMax = 140,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Prehipertensión",
        aumentoLeve = "+3-5",
        aumentoModerado = "+7-9",
        aumentoSevero = "+10-14"
    ),
    PresionArterial(
        edadMin = 70,
        edadMax = 79,
        estadoSalud = "Saludable",
        sistolicaMin = 130,
        sistolicaMax = 145,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Prehipertensión",
        aumentoLeve = "+3-5",
        aumentoModerado = "+8-11",
        aumentoSevero = "+12-16"
    ),
    PresionArterial(
        edadMin = 18,
        edadMax = 29,
        estadoSalud = "Crónica",
        sistolicaMin = 120,
        sistolicaMax = 135,
        diastolicaMin = 80,
        diastolicaMax = 90,
        clasificacion = "Prehipertensión / Hipertensión",
        aumentoLeve = "+3-4",
        aumentoModerado = "+6-8",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 30,
        edadMax = 39,
        estadoSalud = "Crónica",
        sistolicaMin = 125,
        sistolicaMax = 140,
        diastolicaMin = 85,
        diastolicaMax = 95,
        clasificacion = "Hipertensión Grado I",
        aumentoLeve = "+3-5",
        aumentoModerado = "+6-8",
        aumentoSevero = "+10-13"
    ),
    PresionArterial(
        edadMin = 40,
        edadMax = 49,
        estadoSalud = "Crónica",
        sistolicaMin = 130,
        sistolicaMax = 145,
        diastolicaMin = 85,
        diastolicaMax = 95,
        clasificacion = "Hipertensión Grado I o II",
        aumentoLeve = "+4-6",
        aumentoModerado = "+7-10",
        aumentoSevero = "+12-15"
    ),
    PresionArterial(
        edadMin = 50,
        edadMax = 59,
        estadoSalud = "Crónica",
        sistolicaMin = 135,
        sistolicaMax = 150,
        diastolicaMin = 85,
        diastolicaMax = 95,
        clasificacion = "Hipertensión Grado II",
        aumentoLeve = "+3-5",
        aumentoModerado = "+6-9",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 60,
        edadMax = 69,
        estadoSalud = "Crónica",
        sistolicaMin = 140,
        sistolicaMax = 160,
        diastolicaMin = 85,
        diastolicaMax = 95,
        clasificacion = "Hipertensión Grado II o III",
        aumentoLeve = "+5-7",
        aumentoModerado = "+8-12",
        aumentoSevero = "+13-16"
    ),
    PresionArterial(
        edadMin = 70,
        edadMax = 79,
        estadoSalud = "Crónica",
        sistolicaMin = 145,
        sistolicaMax = 165,
        diastolicaMin = 85,
        diastolicaMax = 95,
        clasificacion = "Hipertensión Grado III",
        aumentoLeve = "+6-9",
        aumentoModerado = "+10-14",
        aumentoSevero = "+15-20"
    ),
    PresionArterial(
        edadMin = 18,
        edadMax = 29,
        estadoSalud = "Diabetes",
        sistolicaMin = 80,
        sistolicaMax = 110,
        diastolicaMin = 80,
        diastolicaMax = 90,
        clasificacion = "Normal",
        aumentoLeve = "+3-4",
        aumentoModerado = "+6-8",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 30,
        edadMax = 39,
        estadoSalud = "Diabetes",
        sistolicaMin = 75,
        sistolicaMax = 110,
        diastolicaMin = 80,
        diastolicaMax = 90,
        clasificacion = "Prehipertensión",
        aumentoLeve = "+3-5",
        aumentoModerado = "+6-8",
        aumentoSevero = "+10-13"
    ),
    PresionArterial(
        edadMin = 40,
        edadMax = 49,
        estadoSalud = "Diabetes",
        sistolicaMin = 70,
        sistolicaMax = 90,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado I",
        aumentoLeve = "+4-6",
        aumentoModerado = "+7-9",
        aumentoSevero = "+12-15"
    ),
    PresionArterial(
        edadMin = 50,
        edadMax = 59,
        estadoSalud = "Diabetes",
        sistolicaMin = 70,
        sistolicaMax = 90,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado II",
        aumentoLeve = "+3-5",
        aumentoModerado = "+6-9",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 60,
        edadMax = 69,
        estadoSalud = "Diabetes",
        sistolicaMin = 70,
        sistolicaMax = 85,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado II o III",
        aumentoLeve = "+5-7",
        aumentoModerado = "+8-12",
        aumentoSevero = "+13-16"
    ),
    PresionArterial(
        edadMin = 70,
        edadMax = 79,
        estadoSalud = "Diabetes",
        sistolicaMin = 70,
        sistolicaMax = 85,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado III",
        aumentoLeve = "+3-5",
        aumentoModerado = "+7-9",
        aumentoSevero = "+10-14"
    ),
    PresionArterial(
        edadMin = 18,
        edadMax = 29,
        estadoSalud = "ERC",
        sistolicaMin = 80,
        sistolicaMax = 105,
        diastolicaMin = 80,
        diastolicaMax = 90,
        clasificacion = "Normal",
        aumentoLeve = "+3-5",
        aumentoModerado = "+6-9",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 30,
        edadMax = 39,
        estadoSalud = "ERC",
        sistolicaMin = 75,
        sistolicaMax = 95,
        diastolicaMin = 80,
        diastolicaMax = 90,
        clasificacion = "Prehipertensión",
        aumentoLeve = "+3-5",
        aumentoModerado = "+7-10",
        aumentoSevero = "+12-15"
    ),
    PresionArterial(
        edadMin = 40,
        edadMax = 49,
        estadoSalud = "ERC",
        sistolicaMin = 70,
        sistolicaMax = 90,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado I",
        aumentoLeve = "+3-5",
        aumentoModerado = "+6-9",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 50,
        edadMax = 59,
        estadoSalud = "ERC",
        sistolicaMin = 70,
        sistolicaMax = 85,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado II",
        aumentoLeve = "+5-7",
        aumentoModerado = "+8-12",
        aumentoSevero = "+13-16"
    ),
    PresionArterial(
        edadMin = 60,
        edadMax = 69,
        estadoSalud = "ERC",
        sistolicaMin = 70,
        sistolicaMax = 85,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado II o III",
        aumentoLeve = "+3-5",
        aumentoModerado = "+7-9",
        aumentoSevero = "+10-14"
    ),
    PresionArterial(
        edadMin = 70,
        edadMax = 79,
        estadoSalud = "ERC",
        sistolicaMin = 70,
        sistolicaMax = 85,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado III",
        aumentoLeve = "+5-8",
        aumentoModerado = "+9-13",
        aumentoSevero = "+14-18"
    ),
    PresionArterial(
        edadMin = 18,
        edadMax = 29,
        estadoSalud = "FQ",
        sistolicaMin = 75,
        sistolicaMax = 115,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Normal",
        aumentoLeve = "+3-5",
        aumentoModerado = "+6-9",
        aumentoSevero = "+9-12"
    ),
    PresionArterial(
        edadMin = 30,
        edadMax = 39,
        estadoSalud = "FQ",
        sistolicaMin = 80,
        sistolicaMax = 110,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Prehipertensión",
        aumentoLeve = "+3-5",
        aumentoModerado = "+7-9",
        aumentoSevero = "+10-14"
    ),
    PresionArterial(
        edadMin = 40,
        edadMax = 49,
        estadoSalud = "FQ",
        sistolicaMin = 75,
        sistolicaMax = 95,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado I",
        aumentoLeve = "+5-7",
        aumentoModerado = "+8-12",
        aumentoSevero = "+13-16"
    ),
    PresionArterial(
        edadMin = 50,
        edadMax = 59,
        estadoSalud = "FQ",
        sistolicaMin = 80,
        sistolicaMax = 95,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado II",
        aumentoLeve = "+3-5",
        aumentoModerado = "+7-9",
        aumentoSevero = "+10-14"
    ),
    PresionArterial(
        edadMin = 60,
        edadMax = 69,
        estadoSalud = "FQ",
        sistolicaMin = 80,
        sistolicaMax = 95,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado II o III",
        aumentoLeve = "+5-8",
        aumentoModerado = "+9-13",
        aumentoSevero = "+14-18"
    ),
    PresionArterial(
        edadMin = 70,
        edadMax = 79,
        estadoSalud = "FQ",
        sistolicaMin = 80,
        sistolicaMax = 95,
        diastolicaMin = 75,
        diastolicaMax = 85,
        clasificacion = "Hipertensión Grado III",
        aumentoLeve = "+6-9",
        aumentoModerado = "+10-14",
        aumentoSevero = "+15-20"
    )



)

